// AUTO-GENERATED by gen_lut.py  -- do not edit by hand
// GELU residual PWL LUT : N_SEG=64, width=2^-4, R in Q?.14
// R14 = base14[seg] + (delta14[seg]*frac >>> 7)

reg signed [15:0] base14_rom  [0:63];
reg signed [15:0] delta14_rom [0:63];
initial begin
    base14_rom[ 0]  =       16'sd0; delta14_rom[ 0] =     16'sd486;  // a=0.0000 R=0.000000
    base14_rom[ 1]  =     16'sd486; delta14_rom[ 1] =     16'sd436;  // a=0.0625 R=0.029693
    base14_rom[ 2]  =     16'sd922; delta14_rom[ 2] =     16'sd386;  // a=0.1250 R=0.056283
    base14_rom[ 3]  =    16'sd1308; delta14_rom[ 3] =     16'sd336;  // a=0.1875 R=0.079806
    base14_rom[ 4]  =    16'sd1644; delta14_rom[ 4] =     16'sd288;  // a=0.2500 R=0.100323
    base14_rom[ 5]  =    16'sd1932; delta14_rom[ 5] =     16'sd242;  // a=0.3125 R=0.117916
    base14_rom[ 6]  =    16'sd2174; delta14_rom[ 6] =     16'sd198;  // a=0.3750 R=0.132686
    base14_rom[ 7]  =    16'sd2372; delta14_rom[ 7] =     16'sd156;  // a=0.4375 R=0.144758
    base14_rom[ 8]  =    16'sd2528; delta14_rom[ 8] =     16'sd116;  // a=0.5000 R=0.154269
    base14_rom[ 9]  =    16'sd2644; delta14_rom[ 9] =      16'sd80;  // a=0.5625 R=0.161374
    base14_rom[10]  =    16'sd2724; delta14_rom[10] =      16'sd46;  // a=0.6250 R=0.166241
    base14_rom[11]  =    16'sd2770; delta14_rom[11] =      16'sd15;  // a=0.6875 R=0.169045
    base14_rom[12]  =    16'sd2785; delta14_rom[12] =     -16'sd13;  // a=0.7500 R=0.169971
    base14_rom[13]  =    16'sd2772; delta14_rom[13] =     -16'sd37;  // a=0.8125 R=0.169205
    base14_rom[14]  =    16'sd2735; delta14_rom[14] =     -16'sd59;  // a=0.8750 R=0.166939
    base14_rom[15]  =    16'sd2676; delta14_rom[15] =     -16'sd77;  // a=0.9375 R=0.163360
    base14_rom[16]  =    16'sd2599; delta14_rom[16] =     -16'sd92;  // a=1.0000 R=0.158655
    base14_rom[17]  =    16'sd2507; delta14_rom[17] =    -16'sd105;  // a=1.0625 R=0.153005
    base14_rom[18]  =    16'sd2402; delta14_rom[18] =    -16'sd116;  // a=1.1250 R=0.146581
    base14_rom[19]  =    16'sd2286; delta14_rom[19] =    -16'sd122;  // a=1.1875 R=0.139549
    base14_rom[20]  =    16'sd2164; delta14_rom[20] =    -16'sd128;  // a=1.2500 R=0.132062
    base14_rom[21]  =    16'sd2036; delta14_rom[21] =    -16'sd131;  // a=1.3125 R=0.124262
    base14_rom[22]  =    16'sd1905; delta14_rom[22] =    -16'sd132;  // a=1.3750 R=0.116278
    base14_rom[23]  =    16'sd1773; delta14_rom[23] =    -16'sd131;  // a=1.4375 R=0.108226
    base14_rom[24]  =    16'sd1642; delta14_rom[24] =    -16'sd129;  // a=1.5000 R=0.100211
    base14_rom[25]  =    16'sd1513; delta14_rom[25] =    -16'sd126;  // a=1.5625 R=0.092321
    base14_rom[26]  =    16'sd1387; delta14_rom[26] =    -16'sd122;  // a=1.6250 R=0.084632
    base14_rom[27]  =    16'sd1265; delta14_rom[27] =    -16'sd116;  // a=1.6875 R=0.077209
    base14_rom[28]  =    16'sd1149; delta14_rom[28] =    -16'sd111;  // a=1.7500 R=0.070104
    base14_rom[29]  =    16'sd1038; delta14_rom[29] =    -16'sd104;  // a=1.8125 R=0.063355
    base14_rom[30]  =     16'sd934; delta14_rom[30] =     -16'sd98;  // a=1.8750 R=0.056993
    base14_rom[31]  =     16'sd836; delta14_rom[31] =     -16'sd91;  // a=1.9375 R=0.051038
    base14_rom[32]  =     16'sd745; delta14_rom[32] =     -16'sd83;  // a=2.0000 R=0.045500
    base14_rom[33]  =     16'sd662; delta14_rom[33] =     -16'sd77;  // a=2.0625 R=0.040384
    base14_rom[34]  =     16'sd585; delta14_rom[34] =     -16'sd71;  // a=2.1250 R=0.035686
    base14_rom[35]  =     16'sd514; delta14_rom[35] =     -16'sd63;  // a=2.1875 R=0.031397
    base14_rom[36]  =     16'sd451; delta14_rom[36] =     -16'sd58;  // a=2.2500 R=0.027505
    base14_rom[37]  =     16'sd393; delta14_rom[37] =     -16'sd52;  // a=2.3125 R=0.023992
    base14_rom[38]  =     16'sd341; delta14_rom[38] =     -16'sd46;  // a=2.3750 R=0.020839
    base14_rom[39]  =     16'sd295; delta14_rom[39] =     -16'sd41;  // a=2.4375 R=0.018024
    base14_rom[40]  =     16'sd254; delta14_rom[40] =     -16'sd36;  // a=2.5000 R=0.015524
    base14_rom[41]  =     16'sd218; delta14_rom[41] =     -16'sd32;  // a=2.5625 R=0.013315
    base14_rom[42]  =     16'sd186; delta14_rom[42] =     -16'sd28;  // a=2.6250 R=0.011373
    base14_rom[43]  =     16'sd158; delta14_rom[43] =     -16'sd24;  // a=2.6875 R=0.009674
    base14_rom[44]  =     16'sd134; delta14_rom[44] =     -16'sd21;  // a=2.7500 R=0.008194
    base14_rom[45]  =     16'sd113; delta14_rom[45] =     -16'sd18;  // a=2.8125 R=0.006913
    base14_rom[46]  =      16'sd95; delta14_rom[46] =     -16'sd15;  // a=2.8750 R=0.005808
    base14_rom[47]  =      16'sd80; delta14_rom[47] =     -16'sd14;  // a=2.9375 R=0.004860
    base14_rom[48]  =      16'sd66; delta14_rom[48] =     -16'sd11;  // a=3.0000 R=0.004050
    base14_rom[49]  =      16'sd55; delta14_rom[49] =      -16'sd9;  // a=3.0625 R=0.003361
    base14_rom[50]  =      16'sd46; delta14_rom[50] =      -16'sd9;  // a=3.1250 R=0.002778
    base14_rom[51]  =      16'sd37; delta14_rom[51] =      -16'sd6;  // a=3.1875 R=0.002287
    base14_rom[52]  =      16'sd31; delta14_rom[52] =      -16'sd6;  // a=3.2500 R=0.001875
    base14_rom[53]  =      16'sd25; delta14_rom[53] =      -16'sd5;  // a=3.3125 R=0.001531
    base14_rom[54]  =      16'sd20; delta14_rom[54] =      -16'sd3;  // a=3.3750 R=0.001246
    base14_rom[55]  =      16'sd17; delta14_rom[55] =      -16'sd4;  // a=3.4375 R=0.001009
    base14_rom[56]  =      16'sd13; delta14_rom[56] =      -16'sd2;  // a=3.5000 R=0.000814
    base14_rom[57]  =      16'sd11; delta14_rom[57] =      -16'sd2;  // a=3.5625 R=0.000654
    base14_rom[58]  =       16'sd9; delta14_rom[58] =      -16'sd2;  // a=3.6250 R=0.000524
    base14_rom[59]  =       16'sd7; delta14_rom[59] =      -16'sd2;  // a=3.6875 R=0.000418
    base14_rom[60]  =       16'sd5; delta14_rom[60] =      -16'sd1;  // a=3.7500 R=0.000332
    base14_rom[61]  =       16'sd4; delta14_rom[61] =      -16'sd1;  // a=3.8125 R=0.000262
    base14_rom[62]  =       16'sd3; delta14_rom[62] =       16'sd0;  // a=3.8750 R=0.000207
    base14_rom[63]  =       16'sd3; delta14_rom[63] =      -16'sd1;  // a=3.9375 R=0.000162
end
